import type { User, Client, Opportunity, OpportunityStage, Activity } from './types';

export const users: User[] = [
  { id: 'user-1', name: 'Alex Morgan', avatarUrl: 'https://picsum.photos/seed/user1/40/40', initials: 'AM' },
  { id: 'user-2', name: 'Ben Carter', avatarUrl: 'https://picsum.photos/seed/user2/40/40', initials: 'BC' },
  { id: 'user-3', name: 'Chloe Davis', avatarUrl: 'https://picsum.photos/seed/user3/40/40', initials: 'CD' },
];

export const clients: Client[] = [
  {
    id: 'client-1',
    name: 'Global Media Inc.',
    email: 'contact@globalmedia.com',
    phone: '555-0101',
    company: 'Global Media Inc.',
    avatarUrl: 'https://picsum.photos/seed/client1/40/40',
    avatarFallback: 'GM',
  },
  {
    id: 'client-2',
    name: 'Innovate Solutions',
    email: 'hello@innovatesolutions.io',
    phone: '555-0102',
    company: 'Innovate Solutions',
    avatarUrl: 'https://picsum.photos/seed/client2/40/40',
    avatarFallback: 'IS',
  },
  {
    id: 'client-3',
    name: 'Quantum Leap Tech',
    email: 'info@quantumleap.tech',
    phone: '555-0103',
    company: 'Quantum Leap Tech',
    avatarUrl: 'https://picsum.photos/seed/client3/40/40',
    avatarFallback: 'QL',
  },
    {
    id: 'client-4',
    name: 'Starlight Productions',
    email: 'support@starlight.prod',
    phone: '555-0104',
    company: 'Starlight Productions',
    avatarUrl: 'https://picsum.photos/seed/client4/40/40',
    avatarFallback: 'SP',
  },
    {
    id: 'client-5',
    name: 'Apex Digital',
    email: 'connect@apexdigital.com',
    phone: '555-0105',
    company: 'Apex Digital',
    avatarUrl: 'https://picsum.photos/seed/client5/40/40',
    avatarFallback: 'AD',
  },
];

export const opportunityStages: OpportunityStage[] = [
  'New',
  'Proposal',
  'Negotiation',
  'Closed Won',
  'Closed Lost',
];

export const opportunities: Opportunity[] = [
  {
    id: 'opp-1',
    title: 'Q3 Digital Campaign',
    clientName: 'Global Media Inc.',
    clientId: 'client-1',
    value: 75000,
    stage: 'Negotiation',
    closeDate: '2024-08-15',
    ownerId: 'user-1',
  },
  {
    id: 'opp-2',
    title: 'Website Revamp Project',
    clientName: 'Innovate Solutions',
    clientId: 'client-2',
    value: 120000,
    stage: 'Proposal',
    closeDate: '2024-09-01',
    ownerId: 'user-2',
  },
  {
    id: 'opp-3',
    title: 'Annual Subscription Renewal',
    clientName: 'Quantum Leap Tech',
    clientId: 'client-3',
    value: 45000,
    stage: 'Closed Won',
    closeDate: '2024-07-20',
    ownerId: 'user-1',
  },
  {
    id: 'opp-4',
    title: 'New Product Launch Ad',
    clientName: 'Starlight Productions',
    clientId: 'client-4',
    value: 95000,
    stage: 'New',
    closeDate: '2024-09-30',
    ownerId: 'user-3',
  },
  {
    id: 'opp-5',
    title: 'SEO & Content Strategy',
    clientName: 'Apex Digital',
    clientId: 'client-5',
    value: 30000,
    stage: 'Proposal',
    closeDate: '2024-08-25',
    ownerId: 'user-2',
  },
  {
    id: 'opp-6',
    title: 'Social Media Management',
    clientName: 'Global Media Inc.',
    clientId: 'client-1',
    value: 25000,
    stage: 'New',
    closeDate: '2024-10-10',
    ownerId: 'user-1',
  },
  {
    id: 'opp-7',
    title: 'Mobile App Development',
    clientName: 'Quantum Leap Tech',
    clientId: 'client-3',
    value: 250000,
    stage: 'Closed Lost',
    closeDate: '2024-07-10',
    ownerId: 'user-3',
  },
];

export const activities: Activity[] = [
  {
    id: 'act-1',
    type: 'Meeting',
    subject: 'Initial discovery call',
    date: '2024-07-12',
    notes: 'Discussed project scope and goals. Client is interested in a full proposal.',
    clientId: 'client-4',
    opportunityId: 'opp-4',
  },
  {
    id: 'act-2',
    type: 'Email',
    subject: 'Follow-up on Proposal',
    date: '2024-07-28',
    notes: 'Sent the revised proposal with updated pricing. Awaiting feedback.',
    clientId: 'client-2',
    opportunityId: 'opp-2',
  },
  {
    id: 'act-3',
    type: 'Call',
    subject: 'Contract Negotiation Call',
    date: '2024-08-02',
    notes: 'Discussed final terms of the contract. Minor adjustments requested on payment schedule.',
    clientId: 'client-1',
    opportunityId: 'opp-1',
  },
  {
    id: 'act-4',
    type: 'Note',
    subject: 'Internal Strategy Meeting',
    date: '2024-08-01',
    notes: 'Team meeting to align on the delivery strategy for the SEO project.',
    clientId: 'client-5',
    opportunityId: 'opp-5',
  },
    {
    id: 'act-5',
    type: 'Email',
    subject: 'Welcome & Onboarding',
    date: '2024-07-21',
    notes: 'Sent welcome email and onboarding materials after the deal was won.',
    clientId: 'client-3',
    opportunityId: 'opp-3',
  },
];

export const recentActivities = activities.slice(0, 3);
