import type { CrmModuleDefinition } from './types';

const defineModule = (definition: CrmModuleDefinition): CrmModuleDefinition => definition;

export const crmModuleCatalog = [
  defineModule({
    id: 'dashboard',
    name: 'Dashboard',
    description: 'Resumen operativo y comercial del CRM.',
    version: '1.0.0',
    defaultEnabled: true,
    dependencies: [],
    platforms: ['web', 'android'],
    capabilities: ['dashboard.read'],
  }),
  defineModule({
    id: 'clients',
    name: 'Clientes',
    description: 'Gestión integral de clientes, personas y actividades.',
    version: '1.0.0',
    defaultEnabled: true,
    dependencies: [],
    platforms: ['web', 'android'],
    capabilities: ['clients.read', 'clients.create', 'clients.update', 'clients.delete', 'clients.import', 'clients.export'],
  }),
  defineModule({
    id: 'opportunities',
    name: 'Oportunidades',
    description: 'Pipeline, propuestas y seguimiento de oportunidades.',
    version: '1.0.0',
    defaultEnabled: true,
    dependencies: ['clients'],
    platforms: ['web', 'android'],
    capabilities: ['opportunities.read', 'opportunities.create', 'opportunities.update', 'opportunities.delete', 'opportunities.approve'],
  }),
  defineModule({
    id: 'prospects',
    name: 'Prospectos',
    description: 'Captación, asignación, reclamo y conversión de prospectos.',
    version: '1.0.0',
    defaultEnabled: true,
    dependencies: [],
    platforms: ['web', 'android'],
    capabilities: ['prospects.read', 'prospects.create', 'prospects.update', 'prospects.delete', 'prospects.approve', 'prospects.export'],
    apiVersion: 'v1',
  }),
  defineModule({
    id: 'objectives',
    name: 'Objetivos',
    description: 'Objetivos comerciales, alertas y seguimiento.',
    version: '1.0.0',
    defaultEnabled: true,
    dependencies: ['opportunities', 'prospects'],
    platforms: ['web', 'android'],
    capabilities: ['objectives.read', 'objectives.update', 'objectives.manage'],
  }),
  defineModule({
    id: 'tasks',
    name: 'Tareas',
    description: 'Tareas y recordatorios asociados al trabajo comercial.',
    version: '1.0.0',
    defaultEnabled: true,
    dependencies: ['clients'],
    platforms: ['web', 'android'],
    capabilities: ['tasks.read', 'tasks.create', 'tasks.update', 'tasks.delete'],
  }),
  defineModule({
    id: 'coaching',
    name: 'Seguimiento',
    description: 'Coaching y seguimiento del equipo comercial.',
    version: '1.0.0',
    defaultEnabled: true,
    dependencies: ['prospects', 'opportunities'],
    platforms: ['web', 'android'],
    capabilities: ['coaching.read', 'coaching.create', 'coaching.update', 'coaching.delete', 'coaching.manage'],
  }),
  defineModule({
    id: 'programming',
    name: 'Programación',
    description: 'Grilla, programas, acciones vigentes y PNT.',
    version: '1.0.0',
    defaultEnabled: true,
    dependencies: [],
    platforms: ['web', 'android'],
    capabilities: ['programming.read', 'programming.create', 'programming.update', 'programming.delete', 'programming.manage'],
  }),
  defineModule({
    id: 'advertising',
    name: 'Publicidad',
    description: 'Órdenes de publicidad y pautas comerciales.',
    version: '1.0.0',
    defaultEnabled: true,
    dependencies: ['clients', 'opportunities', 'programming'],
    platforms: ['web', 'android'],
    capabilities: ['advertising.read', 'advertising.create', 'advertising.update', 'advertising.delete', 'advertising.approve', 'advertising.export'],
  }),
  defineModule({
    id: 'content',
    name: 'Contenidos',
    description: 'Notas comerciales, notas web y pedidos de redes.',
    version: '1.0.0',
    defaultEnabled: true,
    dependencies: ['clients'],
    platforms: ['web', 'android'],
    capabilities: ['content.read', 'content.create', 'content.update', 'content.delete', 'content.approve', 'content.export'],
  }),
  defineModule({
    id: 'approvals',
    name: 'Aprobaciones',
    description: 'Bandeja y circuitos de aprobación transversales.',
    version: '1.0.0',
    defaultEnabled: true,
    dependencies: [],
    platforms: ['web', 'android'],
    capabilities: ['approvals.read', 'approvals.approve', 'approvals.manage'],
  }),
  defineModule({
    id: 'calendar',
    name: 'Calendario',
    description: 'Agenda, eventos e integración con calendarios.',
    version: '1.0.0',
    defaultEnabled: true,
    dependencies: ['integrations'],
    platforms: ['web', 'android'],
    capabilities: ['calendar.read', 'calendar.create', 'calendar.update', 'calendar.delete'],
  }),
  defineModule({
    id: 'billing',
    name: 'Facturación y cobranzas',
    description: 'Facturación, cobranzas y solicitudes de facturación.',
    version: '1.0.0',
    defaultEnabled: true,
    dependencies: ['clients', 'opportunities'],
    platforms: ['web', 'android'],
    capabilities: ['billing.read', 'billing.create', 'billing.update', 'billing.delete', 'billing.approve', 'billing.import', 'billing.export'],
    apiVersion: 'v1',
  }),
  defineModule({
    id: 'exchanges',
    name: 'Canjes y necesidades',
    description: 'Necesidades, convenios y gestión de canjes.',
    version: '1.0.0',
    defaultEnabled: true,
    dependencies: ['clients'],
    platforms: ['web', 'android'],
    capabilities: ['exchanges.read', 'exchanges.create', 'exchanges.update', 'exchanges.delete', 'exchanges.approve', 'exchanges.manage'],
  }),
  defineModule({
    id: 'human-resources',
    name: 'Recursos Humanos',
    description: 'Licencias y operaciones del equipo.',
    version: '1.0.0',
    defaultEnabled: true,
    dependencies: [],
    platforms: ['web', 'android'],
    capabilities: ['human-resources.read', 'human-resources.create', 'human-resources.update', 'human-resources.delete', 'human-resources.approve'],
  }),
  defineModule({
    id: 'reporting',
    name: 'Reportes',
    description: 'Indicadores y reportes transversales.',
    version: '1.0.0',
    defaultEnabled: true,
    dependencies: [],
    platforms: ['web', 'android'],
    capabilities: ['reporting.read', 'reporting.export'],
  }),
  defineModule({
    id: 'administration',
    name: 'Administración',
    description: 'Usuarios, permisos, configuración e importaciones.',
    version: '1.0.0',
    defaultEnabled: true,
    dependencies: [],
    platforms: ['web', 'android'],
    capabilities: ['administration.read', 'administration.update', 'administration.manage', 'administration.import', 'administration.export'],
  }),
  defineModule({
    id: 'integrations',
    name: 'Integraciones',
    description: 'Servicios externos como Google y Tango.',
    version: '1.0.0',
    defaultEnabled: true,
    dependencies: [],
    platforms: ['web', 'android'],
    capabilities: ['integrations.read', 'integrations.manage', 'integrations.import', 'integrations.export'],
  }),
] as const satisfies readonly CrmModuleDefinition[];
